"""Builds an original, per-game analytical breakdown for a whole week.

Structurally inspired by the format of fantasy-football "worksheet"-style
previews (a team-vs-team stat comparison table with league ranks, plus a
short written takeaway per game) -- but every number here comes from data
this app already pulls live (Sleeper's schedule, DraftKings' real salaries,
nflverse's real closing lines and box scores), and every sentence is
generated by the template logic in this file from those real numbers. None
of it reproduces any outside site's actual written analysis, opinions, or
player-specific commentary.

Ranks are always "1 = best for that side of the ball" (e.g. rank 1 in
yards allowed/play is the stingiest defense, not the most yards allowed),
computed among whichever teams have a trailing value at that point in the
season -- so a rank of 1 in Week 1 just means "the only team with data."
"""
from __future__ import annotations

from app import nflverse_client as nc
from app import slates as slates_module
from app.models import Game, GameBreakdown, TeamStatLine, TopPlayer, WeekBreakdown
from app.schedule import get_week_schedule

_RANK_WINDOW = 8            # trailing games used for all league-rank context
_FUNNEL_RANK_THRESHOLD = 10  # a defense ranking in the top 10 of 32 counts as a real funnel
_PACE_RANK_THRESHOLD = 10
_EFFICIENCY_RANK_THRESHOLD = 10
_TOP_PLAYERS_PER_TEAM = 3

# metric -> whether a *higher* trailing value means a better rank (1st)
_RANK_DIRECTION = {
    "points_for": True,
    "points_against": False,
    "yards_per_play": True,
    "yards_allowed_per_play": False,
    "plays": True,
    "opp_pass_pct_allowed": True,   # rank 1 = biggest pass funnel
    "opp_rush_pct_allowed": True,   # rank 1 = biggest rush funnel
}


def _ordinal(n: int) -> str:
    if 10 <= n % 100 <= 20:
        suffix = "th"
    else:
        suffix = {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")
    return f"{n}{suffix}"


def _build_team_stats(index: dict, team: str, season: int, week: int, ranks: dict[str, dict[str, int]]) -> TeamStatLine:
    def trail(metric: str) -> float | None:
        return nc.team_trailing(index, team, metric, season, week, _RANK_WINDOW)

    return TeamStatLine(
        team=team,
        points_for=trail("points_for"),
        points_for_rank=ranks["points_for"].get(team),
        points_against=trail("points_against"),
        points_against_rank=ranks["points_against"].get(team),
        yards_per_play=trail("yards_per_play"),
        yards_per_play_rank=ranks["yards_per_play"].get(team),
        yards_allowed_per_play=trail("yards_allowed_per_play"),
        yards_allowed_per_play_rank=ranks["yards_allowed_per_play"].get(team),
        pace_plays=trail("plays"),
        pace_rank=ranks["plays"].get(team),
        pass_pct=trail("pass_pct"),
        rush_pct=trail("rush_pct"),
        opp_pass_pct_allowed=trail("opp_pass_pct_allowed"),
        opp_pass_pct_allowed_rank=ranks["opp_pass_pct_allowed"].get(team),
        opp_rush_pct_allowed=trail("opp_rush_pct_allowed"),
        opp_rush_pct_allowed_rank=ranks["opp_rush_pct_allowed"].get(team),
    )


def _vegas_takeaways(
    game: Game, total_rank: int | None, away_implied_rank: int | None, home_implied_rank: int | None
) -> list[str]:
    ctx = game.context
    if ctx is None or ctx.total_line is None:
        return []

    bullets = []

    total_txt = f"O/U is {ctx.total_line:g}"
    if total_rank is not None:
        total_txt += f" ({_ordinal(total_rank)}-highest total of the week)"
    if ctx.home_spread is not None:
        if abs(ctx.home_spread) < 0.5:
            total_txt += ", a pick'em."
        else:
            fav, line = (game.home, -ctx.home_spread) if ctx.home_spread < 0 else (game.away, ctx.home_spread)
            total_txt += f", with {fav} favored by {line:g}."
        bullets.append(total_txt)

    if ctx.away_implied_total is not None and ctx.home_implied_total is not None:
        away_txt = f"{game.away} is implied for {ctx.away_implied_total:g}"
        if away_implied_rank is not None:
            away_txt += f" ({_ordinal(away_implied_rank)}-highest team total of the week)"
        home_txt = f"{game.home} for {ctx.home_implied_total:g}"
        if home_implied_rank is not None:
            home_txt += f" ({_ordinal(home_implied_rank)})"
        bullets.append(f"{away_txt}; {home_txt}.")

    return bullets


def _pace_takeaway(game: Game, away: TeamStatLine, home: TeamStatLine) -> str | None:
    if away.pace_rank is None or home.pace_rank is None:
        return None

    bottom_cutoff = 32 - _PACE_RANK_THRESHOLD + 1
    if away.pace_rank <= _PACE_RANK_THRESHOLD and home.pace_rank <= _PACE_RANK_THRESHOLD:
        return (
            f"Both offenses rank in the top {_PACE_RANK_THRESHOLD} for plays/game "
            f"({game.away} {_ordinal(away.pace_rank)}, {game.home} {_ordinal(home.pace_rank)}) -- "
            f"expect a plays-heavy environment."
        )
    if away.pace_rank >= bottom_cutoff and home.pace_rank >= bottom_cutoff:
        return (
            f"Both offenses rank in the bottom {_PACE_RANK_THRESHOLD} for plays/game "
            f"({game.away} {_ordinal(away.pace_rank)}, {game.home} {_ordinal(home.pace_rank)}) -- "
            f"expect a slower, more deliberate script."
        )
    if away.pace_rank < home.pace_rank:
        return f"{game.away} plays at a notably faster pace ({_ordinal(away.pace_rank)} in plays/gm) than {game.home} ({_ordinal(home.pace_rank)})."
    return f"{game.home} plays at a notably faster pace ({_ordinal(home.pace_rank)} in plays/gm) than {game.away} ({_ordinal(away.pace_rank)})."


def _funnel_takeaways(game: Game, away: TeamStatLine, home: TeamStatLine) -> list[str]:
    bullets = []

    # away's offense against home's defense
    if home.opp_pass_pct_allowed_rank is not None and home.opp_pass_pct_allowed_rank <= _FUNNEL_RANK_THRESHOLD:
        bullets.append(
            f"{game.away}'s passing game projects for extra volume: {game.home}'s defense ranks "
            f"{_ordinal(home.opp_pass_pct_allowed_rank)} in opponent pass rate faced, a real pass funnel."
        )
    elif home.opp_rush_pct_allowed_rank is not None and home.opp_rush_pct_allowed_rank <= _FUNNEL_RANK_THRESHOLD:
        bullets.append(
            f"{game.away}'s ground game gets a runway: {game.home}'s defense ranks "
            f"{_ordinal(home.opp_rush_pct_allowed_rank)} in opponent rush rate faced, a real rush funnel."
        )

    # home's offense against away's defense
    if away.opp_pass_pct_allowed_rank is not None and away.opp_pass_pct_allowed_rank <= _FUNNEL_RANK_THRESHOLD:
        bullets.append(
            f"{game.home}'s passing game projects for extra volume: {game.away}'s defense ranks "
            f"{_ordinal(away.opp_pass_pct_allowed_rank)} in opponent pass rate faced, a real pass funnel."
        )
    elif away.opp_rush_pct_allowed_rank is not None and away.opp_rush_pct_allowed_rank <= _FUNNEL_RANK_THRESHOLD:
        bullets.append(
            f"{game.home}'s ground game gets a runway: {game.away}'s defense ranks "
            f"{_ordinal(away.opp_rush_pct_allowed_rank)} in opponent rush rate faced, a real rush funnel."
        )

    return bullets


def _efficiency_takeaway(game: Game, away: TeamStatLine, home: TeamStatLine) -> str | None:
    bottom_cutoff = 32 - _EFFICIENCY_RANK_THRESHOLD + 1

    if (
        away.yards_per_play_rank is not None and away.yards_per_play_rank <= _EFFICIENCY_RANK_THRESHOLD
        and home.yards_allowed_per_play_rank is not None and home.yards_allowed_per_play_rank >= bottom_cutoff
    ):
        return (
            f"{game.away}'s offense ({_ordinal(away.yards_per_play_rank)} in yards/play) meets a {game.home} defense "
            f"that ranks {_ordinal(home.yards_allowed_per_play_rank)} in yards/play allowed -- a clear efficiency mismatch."
        )
    if (
        home.yards_per_play_rank is not None and home.yards_per_play_rank <= _EFFICIENCY_RANK_THRESHOLD
        and away.yards_allowed_per_play_rank is not None and away.yards_allowed_per_play_rank >= bottom_cutoff
    ):
        return (
            f"{game.home}'s offense ({_ordinal(home.yards_per_play_rank)} in yards/play) meets a {game.away} defense "
            f"that ranks {_ordinal(away.yards_allowed_per_play_rank)} in yards/play allowed -- a clear efficiency mismatch."
        )
    return None


def generate_takeaways(
    game: Game,
    away: TeamStatLine,
    home: TeamStatLine,
    *,
    total_rank: int | None = None,
    away_implied_rank: int | None = None,
    home_implied_rank: int | None = None,
) -> list[str]:
    bullets: list[str] = []
    bullets.extend(_vegas_takeaways(game, total_rank, away_implied_rank, home_implied_rank))

    pace = _pace_takeaway(game, away, home)
    if pace:
        bullets.append(pace)

    bullets.extend(_funnel_takeaways(game, away, home))

    efficiency = _efficiency_takeaway(game, away, home)
    if efficiency:
        bullets.append(efficiency)

    if not bullets:
        bullets.append("No standout statistical edge for either side yet -- an early-season, projection-neutral matchup.")

    return bullets


async def _top_players_by_team(season: int, week: int) -> dict[str, list[TopPlayer]]:
    try:
        classic = await slates_module.get_slate_players(season, week, "classic")
    except Exception:
        return {}

    by_team: dict[str, list] = {}
    for p in classic.players:
        by_team.setdefault(p.team, []).append(p)

    result: dict[str, list[TopPlayer]] = {}
    for team, players in by_team.items():
        top = sorted(players, key=lambda p: p.salary, reverse=True)[:_TOP_PLAYERS_PER_TEAM]
        result[team] = [TopPlayer(name=p.name, position=p.position, salary=p.salary, trend_l3=p.trend_l3) for p in top]
    return result


async def build_week_breakdown(season: int, week: int) -> WeekBreakdown:
    schedule = await get_week_schedule(season, week)
    index = await nc.get_team_context_trailing_index(season)

    ranks = {
        metric: nc.rank_teams(index, metric, season, week, n=_RANK_WINDOW, descending=direction)
        for metric, direction in _RANK_DIRECTION.items()
    }

    implied_by_team: dict[str, float] = {}
    total_by_game: dict[str, float] = {}
    for g in schedule.games:
        if g.context is None:
            continue
        if g.context.away_implied_total is not None:
            implied_by_team[g.away] = g.context.away_implied_total
        if g.context.home_implied_total is not None:
            implied_by_team[g.home] = g.context.home_implied_total
        if g.context.total_line is not None:
            total_by_game[g.game_id] = g.context.total_line

    implied_rank_this_week = {
        team: i + 1 for i, (team, _v) in enumerate(sorted(implied_by_team.items(), key=lambda kv: kv[1], reverse=True))
    }
    total_rank_this_week = {
        gid: i + 1 for i, (gid, _v) in enumerate(sorted(total_by_game.items(), key=lambda kv: kv[1], reverse=True))
    }

    top_players = await _top_players_by_team(season, week)

    games_out: list[GameBreakdown] = []
    for g in schedule.games:
        away_stats = _build_team_stats(index, g.away, season, week, ranks)
        home_stats = _build_team_stats(index, g.home, season, week, ranks)
        takeaways = generate_takeaways(
            g,
            away_stats,
            home_stats,
            total_rank=total_rank_this_week.get(g.game_id),
            away_implied_rank=implied_rank_this_week.get(g.away),
            home_implied_rank=implied_rank_this_week.get(g.home),
        )
        games_out.append(
            GameBreakdown(
                game=g,
                away_stats=away_stats,
                home_stats=home_stats,
                total_rank_this_week=total_rank_this_week.get(g.game_id),
                away_implied_rank_this_week=implied_rank_this_week.get(g.away),
                home_implied_rank_this_week=implied_rank_this_week.get(g.home),
                takeaways=takeaways,
                away_top_players=top_players.get(g.away, []),
                home_top_players=top_players.get(g.home, []),
            )
        )

    return WeekBreakdown(season=season, week=week, games=games_out)
