"""Builds an original, per-game analytical breakdown for a whole week.

Structurally inspired by the format of fantasy-football "worksheet"-style
previews (a team-vs-team stat comparison table with league ranks, plus a
short written takeaway per game) -- but every number here comes from data
this app already pulls live (Sleeper's schedule, DraftKings' real salaries,
nflverse's real closing lines and box scores), and every sentence is
generated by the template logic in this file from those real numbers. None
of it reproduces any outside site's actual written analysis, opinions, or
player-specific commentary.

Ranks are always "1 = best for that side of the ball" (e.g. rank 1 in
yards allowed/play is the stingiest defense, not the most yards allowed),
computed among whichever teams have a trailing value at that point in the
season -- so a rank of 1 in Week 1 just means "the only team with data."
"""
from __future__ import annotations

from dataclasses import dataclass

from app import ceiling, targets
from app import nflverse_client as nc
from app import slates as slates_module
from app.models import Game, GameBreakdown, TeamStatLine, WeekBreakdown
from app.schedule import get_week_schedule

_RANK_WINDOW = 8            # trailing games for league-rank context (tendency metrics use season-to-date; see nc.TENDENCY_METRICS)
_FUNNEL_RANK_THRESHOLD = 10  # a defense ranking in the top 10 of 32 counts as a real funnel
_PACE_RANK_THRESHOLD = 10
_PACE_GAP_THRESHOLD = 10     # ranks apart before one offense counts as notably faster...
_PACE_GAP_SECS = 1.5         # ...and seconds per snap apart
_EFFICIENCY_RANK_THRESHOLD = 10

# metric -> whether a *higher* trailing value means a better rank (1st)
_RANK_DIRECTION = {
    "points_for": True,
    "points_against": False,
    "yards_per_play": True,
    "yards_allowed_per_play": False,
    "plays": True,
    "neutral_secs": False,          # rank 1 = fastest tempo (fewest seconds per snap)
    "opp_pass_pct_allowed": True,   # rank 1 = biggest pass funnel
    "opp_rush_pct_allowed": True,   # rank 1 = biggest rush funnel
}


def _ordinal(n: int) -> str:
    if 10 <= n % 100 <= 20:
        suffix = "th"
    else:
        suffix = {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")
    return f"{n}{suffix}"


def _build_team_stats(index: dict, team: str, season: int, week: int, ranks: dict[str, dict[str, int]]) -> TeamStatLine:
    def trail(metric: str) -> float | None:
        return nc.team_trailing(index, team, metric, season, week, _RANK_WINDOW)

    return TeamStatLine(
        team=team,
        points_for=trail("points_for"),
        points_for_rank=ranks["points_for"].get(team),
        points_against=trail("points_against"),
        points_against_rank=ranks["points_against"].get(team),
        yards_per_play=trail("yards_per_play"),
        yards_per_play_rank=ranks["yards_per_play"].get(team),
        yards_allowed_per_play=trail("yards_allowed_per_play"),
        yards_allowed_per_play_rank=ranks["yards_allowed_per_play"].get(team),
        plays_per_game=trail("plays"),
        plays_rank=ranks["plays"].get(team),
        tempo_secs=trail("neutral_secs"),
        tempo_rank=ranks["neutral_secs"].get(team),
        pass_pct=trail("pass_pct"),
        rush_pct=trail("rush_pct"),
        opp_pass_pct_allowed=trail("opp_pass_pct_allowed"),
        opp_pass_pct_allowed_rank=ranks["opp_pass_pct_allowed"].get(team),
        opp_rush_pct_allowed=trail("opp_rush_pct_allowed"),
        opp_rush_pct_allowed_rank=ranks["opp_rush_pct_allowed"].get(team),
    )


def _vegas_takeaways(
    game: Game, total_rank: int | None, away_implied_rank: int | None, home_implied_rank: int | None
) -> list[str]:
    ctx = game.context
    if ctx is None or ctx.total_line is None:
        return []

    bullets = []

    total_txt = f"O/U is {ctx.total_line:g}"
    if total_rank is not None:
        total_txt += f" ({_ordinal(total_rank)}-highest total of the week)"
    if ctx.home_spread is not None:
        if abs(ctx.home_spread) < 0.5:
            total_txt += ", a pick'em."
        else:
            fav, line = (game.home, -ctx.home_spread) if ctx.home_spread < 0 else (game.away, ctx.home_spread)
            total_txt += f", with {fav} favored by {line:g}."
        bullets.append(total_txt)

    if ctx.away_implied_total is not None and ctx.home_implied_total is not None:
        away_txt = f"{game.away} is implied for {ctx.away_implied_total:g}"
        if away_implied_rank is not None:
            away_txt += f" ({_ordinal(away_implied_rank)}-highest team total of the week)"
        home_txt = f"{game.home} for {ctx.home_implied_total:g}"
        if home_implied_rank is not None:
            home_txt += f" ({_ordinal(home_implied_rank)})"
        bullets.append(f"{away_txt}; {home_txt}.")

    return bullets


def _pace_takeaway(game: Game, away: TeamStatLine, home: TeamStatLine) -> str | None:
    """Tempo: neutral-situation seconds from snap to snap (not plays/game,
    which also reflects possessions and game script)."""
    if away.tempo_rank is None or home.tempo_rank is None:
        return None

    def fmt(team: str, s: TeamStatLine) -> str:
        return f"{team} {_ordinal(s.tempo_rank)}, {s.tempo_secs:.1f}s/snap"

    bottom_cutoff = 32 - _PACE_RANK_THRESHOLD + 1
    if away.tempo_rank <= _PACE_RANK_THRESHOLD and home.tempo_rank <= _PACE_RANK_THRESHOLD:
        return (
            f"Both offenses play fast in neutral situations ({fmt(game.away, away)}; {fmt(game.home, home)}) -- "
            f"expect extra snaps."
        )
    if away.tempo_rank >= bottom_cutoff and home.tempo_rank >= bottom_cutoff:
        return (
            f"Both offenses play slow in neutral situations ({fmt(game.away, away)}; {fmt(game.home, home)}) -- "
            f"expect fewer snaps and a more deliberate game."
        )
    if abs(away.tempo_rank - home.tempo_rank) < _PACE_GAP_THRESHOLD or abs(away.tempo_secs - home.tempo_secs) < _PACE_GAP_SECS:
        return None
    fast, slow = ((game.away, away), (game.home, home)) if away.tempo_rank < home.tempo_rank else ((game.home, home), (game.away, away))
    return f"{fast[0]} plays notably faster in neutral situations ({fmt(*fast)}) than {slow[0]} ({fmt(*slow)})."


def _funnel_takeaways(game: Game, away: TeamStatLine, home: TeamStatLine) -> list[str]:
    bullets = []

    # away's offense against home's defense
    if home.opp_pass_pct_allowed_rank is not None and home.opp_pass_pct_allowed_rank <= _FUNNEL_RANK_THRESHOLD:
        bullets.append(
            f"{game.away}'s passing game projects for extra volume: {game.home}'s defense ranks "
            f"{_ordinal(home.opp_pass_pct_allowed_rank)} in neutral pass rate faced, a real pass funnel."
        )
    elif home.opp_rush_pct_allowed_rank is not None and home.opp_rush_pct_allowed_rank <= _FUNNEL_RANK_THRESHOLD:
        bullets.append(
            f"{game.away}'s ground game gets a runway: {game.home}'s defense ranks "
            f"{_ordinal(home.opp_rush_pct_allowed_rank)} in neutral rush rate faced, a real rush funnel."
        )

    # home's offense against away's defense
    if away.opp_pass_pct_allowed_rank is not None and away.opp_pass_pct_allowed_rank <= _FUNNEL_RANK_THRESHOLD:
        bullets.append(
            f"{game.home}'s passing game projects for extra volume: {game.away}'s defense ranks "
            f"{_ordinal(away.opp_pass_pct_allowed_rank)} in neutral pass rate faced, a real pass funnel."
        )
    elif away.opp_rush_pct_allowed_rank is not None and away.opp_rush_pct_allowed_rank <= _FUNNEL_RANK_THRESHOLD:
        bullets.append(
            f"{game.home}'s ground game gets a runway: {game.away}'s defense ranks "
            f"{_ordinal(away.opp_rush_pct_allowed_rank)} in neutral rush rate faced, a real rush funnel."
        )

    return bullets


def _efficiency_takeaway(game: Game, away: TeamStatLine, home: TeamStatLine) -> str | None:
    bottom_cutoff = 32 - _EFFICIENCY_RANK_THRESHOLD + 1

    if (
        away.yards_per_play_rank is not None and away.yards_per_play_rank <= _EFFICIENCY_RANK_THRESHOLD
        and home.yards_allowed_per_play_rank is not None and home.yards_allowed_per_play_rank >= bottom_cutoff
    ):
        return (
            f"{game.away}'s offense ({_ordinal(away.yards_per_play_rank)} in yards/play) meets a {game.home} defense "
            f"that ranks {_ordinal(home.yards_allowed_per_play_rank)} in yards/play allowed -- a clear efficiency mismatch."
        )
    if (
        home.yards_per_play_rank is not None and home.yards_per_play_rank <= _EFFICIENCY_RANK_THRESHOLD
        and away.yards_allowed_per_play_rank is not None and away.yards_allowed_per_play_rank >= bottom_cutoff
    ):
        return (
            f"{game.home}'s offense ({_ordinal(home.yards_per_play_rank)} in yards/play) meets a {game.away} defense "
            f"that ranks {_ordinal(away.yards_allowed_per_play_rank)} in yards/play allowed -- a clear efficiency mismatch."
        )
    return None


def generate_takeaways(
    game: Game,
    away: TeamStatLine,
    home: TeamStatLine,
    *,
    total_rank: int | None = None,
    away_implied_rank: int | None = None,
    home_implied_rank: int | None = None,
) -> list[str]:
    bullets: list[str] = []
    bullets.extend(_vegas_takeaways(game, total_rank, away_implied_rank, home_implied_rank))

    pace = _pace_takeaway(game, away, home)
    if pace:
        bullets.append(pace)

    bullets.extend(_funnel_takeaways(game, away, home))

    efficiency = _efficiency_takeaway(game, away, home)
    if efficiency:
        bullets.append(efficiency)

    if not bullets:
        bullets.append("No standout statistical edge for either side yet -- an early-season, projection-neutral matchup.")

    return bullets


@dataclass
class WeekData:
    """Everything the breakdown and game-detail views compute from, loaded once."""

    season: int
    week: int
    schedule: object
    index: dict
    ranks: dict[str, dict[str, int]]
    pass_rate_rank: dict[str, int]
    implied_rank: dict[str, int]
    total_rank: dict[str, int]
    ceiling_ctx: ceiling.CeilingContext
    players: list
    dst_rank: dict[str, int]
    league_sacks: float | None
    league_giveaways: float | None


async def load_week(season: int, week: int) -> WeekData:
    schedule = await get_week_schedule(season, week)
    index = await nc.get_team_context_trailing_index(season)

    ranks = {
        metric: nc.rank_teams(index, metric, season, week, n=_RANK_WINDOW, descending=direction)
        for metric, direction in _RANK_DIRECTION.items()
    }

    implied_by_team: dict[str, float] = {}
    total_by_game: dict[str, float] = {}
    for g in schedule.games:
        if g.context is None:
            continue
        if g.context.away_implied_total is not None:
            implied_by_team[g.away] = g.context.away_implied_total
        if g.context.home_implied_total is not None:
            implied_by_team[g.home] = g.context.home_implied_total
        if g.context.total_line is not None:
            total_by_game[g.game_id] = g.context.total_line

    try:
        players = (await slates_module.get_slate_players(season, week, "classic")).players
    except Exception:
        players = []

    ceiling_ctx = await ceiling.build_context(season, week, schedule)

    def league_avg(metric: str) -> float | None:
        vals = [v for t in index if (v := nc.team_trailing(index, t, metric, season, week, _RANK_WINDOW)) is not None]
        return sum(vals) / len(vals) if vals else None

    return WeekData(
        season=season,
        week=week,
        schedule=schedule,
        index=index,
        ranks=ranks,
        pass_rate_rank=nc.rank_teams(index, "pass_pct", season, week, n=_RANK_WINDOW, descending=True),
        implied_rank={t: i + 1 for i, (t, _v) in enumerate(sorted(implied_by_team.items(), key=lambda kv: kv[1], reverse=True))},
        total_rank={gid: i + 1 for i, (gid, _v) in enumerate(sorted(total_by_game.items(), key=lambda kv: kv[1], reverse=True))},
        ceiling_ctx=ceiling_ctx,
        players=players,
        dst_rank=targets.dst_ceiling_ranks(players, ceiling_ctx),
        league_sacks=league_avg("sacks_taken"),
        league_giveaways=league_avg("giveaways"),
    )


def game_breakdown(wd: WeekData, g: Game) -> GameBreakdown:
    away_stats = _build_team_stats(wd.index, g.away, wd.season, wd.week, wd.ranks)
    home_stats = _build_team_stats(wd.index, g.home, wd.season, wd.week, wd.ranks)
    takeaways = generate_takeaways(
        g,
        away_stats,
        home_stats,
        total_rank=wd.total_rank.get(g.game_id),
        away_implied_rank=wd.implied_rank.get(g.away),
        home_implied_rank=wd.implied_rank.get(g.home),
    )

    def team_targets(team: str, opp: str, stats: TeamStatLine):
        picks = targets.pick_targets(wd.players, team, opp, wd.ceiling_ctx, wd.pass_rate_rank.get(team), stats.pass_pct)
        dst = targets.pick_dst(
            wd.players, team, opp, wd.ceiling_ctx,
            opp_sacks=nc.team_trailing(wd.index, opp, "sacks_taken", wd.season, wd.week, _RANK_WINDOW),
            opp_giveaways=nc.team_trailing(wd.index, opp, "giveaways", wd.season, wd.week, _RANK_WINDOW),
            league_sacks=wd.league_sacks, league_giveaways=wd.league_giveaways,
            opp_implied_rank=wd.implied_rank.get(opp), n_teams=len(wd.implied_rank),
            dst_rank=wd.dst_rank.get(team), n_dst=len(wd.dst_rank),
        )
        return picks + ([dst] if dst else [])

    return GameBreakdown(
        game=g,
        away_stats=away_stats,
        home_stats=home_stats,
        total_rank_this_week=wd.total_rank.get(g.game_id),
        away_implied_rank_this_week=wd.implied_rank.get(g.away),
        home_implied_rank_this_week=wd.implied_rank.get(g.home),
        takeaways=takeaways,
        away_top_players=team_targets(g.away, g.home, away_stats),
        home_top_players=team_targets(g.home, g.away, home_stats),
    )


async def build_week_breakdown(season: int, week: int) -> WeekBreakdown:
    wd = await load_week(season, week)
    return WeekBreakdown(season=season, week=week, games=[game_breakdown(wd, g) for g in wd.schedule.games])
